# This rule is not used by the project ofbiz-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to ofbiz.ofbiz.apache.org resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ofbiz-operator
    app.kubernetes.io/managed-by: kustomize
  name: ofbiz-viewer-role
rules:
- apiGroups:
  - ofbiz.ofbiz.apache.org
  resources:
  - ofbizzes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ofbiz.ofbiz.apache.org
  resources:
  - ofbizzes/status
  verbs:
  - get
