---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  - secrets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ofbiz.ofbiz.apache.org
  resources:
  - ofbizzes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ofbiz.ofbiz.apache.org
  resources:
  - ofbizzes/finalizers
  verbs:
  - update
- apiGroups:
  - ofbiz.ofbiz.apache.org
  resources:
  - ofbizzes/status
  verbs:
  - get
  - patch
  - update
