apiVersion: ofbiz.ofbiz.apache.org/v1alpha1
kind: Ofbiz
metadata:
  labels:
    app.kubernetes.io/name: ofbiz-operator
    app.kubernetes.io/managed-by: kustomize
  name: ofbiz-sample
spec:
  # TODO(user): Add fields here
